### ISSUE TITLE
Overflow in Mobile View

### ISSUE THREAD

**Issue by TartejBrothers** [pippim/pippim.github.io#3]
There is a little overflow in mobile view, you can fix it by using
```css
body{
     overflow-x:hidden;
}
```

**Comment by pippim** [comment]
I've researched this and found a **Stack Overflow** answer: 

- https://stackoverflow.com/a/13019607/6929343

It recommends:

``` css
html, body {
  overflow-x: hidden;
}
```

For testing purposes can you provide an example (screenshot perhaps) where overflow is a problem?

Thanks

**Comment by TartejBrothers** [comment]
- Yes this should work, first try just doing
```css
body{
     overflow-x:hidden;
}
```
<img width="390" alt="image" src="https://github.com/pippim/pippim.github.io/assets/112921727/9b62d156-f6cb-47ec-8d4e-c5ea2eeb93ca">

- As you can see, if you scroll your website on phone horizontally, then there is black space coming in and removing the left side.
- With `overflow-x`, the user won't be able to scroll horizontally, and it will fix this problem.

**Comment by pippim** [comment]
Thank you for the screenshot. Digging a little deeper I found this:
![website directory tree display bug](https://github.com/pippim/pippim.github.io/assets/92641463/f7c2fc94-7a0a-47d9-8598-631a6162f8e1)

The image is ending too far to the right. After this is fixed the scroll issue should be fixed.

I'm investigating and hope to find the problem soon.

**Comment by pippim** [comment]
On the Answers page, when you expand Post Tags for `h` to `k` tags it shows:
![answer posts display bug](https://github.com/pippim/pippim.github.io/assets/92641463/a0a0f337-b89d-4274-a976-0b578fa73059)

In this case, the ability to scroll to the right is needed, to see the Red mark of total post counts in `hardware-test` to `hddtemp` tag names.

**Comment by pippim** [comment]
The original overflow problem likely occurred a few months ago. It has been fixed by adding `margin-left` in `/assets/css/style.scss` as show below:

``` scss
// For website_tree.txt in index.md
.line-draw pre,
.line-draw .highlight,
.line-draw .highlight pre,
.line-draw {  // from: /_includes/tcm-common-code.js #tcmLineDraw
    font-family: Consolas, "Liberation Mono", Menlo, Courier,
                 "Courier New", monospace ! important;
    // font-size: 1.5rem ! important;  // increases line spacing not font
    line-height: 1.14 ! important;
    margin-left: 0px;
}
```
